= Code de Conduite des Contributeurs (CCC)

:nom: [NOM]
:adresse: [ADRESSE]
:email: [EMAIL]
:date: [DATE]

:http_cgc: [HTTP/CGC]
:http_ccc: [HTTP/CCC]

:ref: ***

********
Par : {nom}, {adresse} (ci-après nommé {ref}) +
État au : {date} | Consultable depuis l’adresse : {http_ccc} +
Annexe : Conditions Générales de Contribution | Consultable depuis l’adresse : {http_cgc}
********

== Notre engagement

Dans l’intérêt de favoriser un environnement ouvert et accueillant, nous Contributeurs, en tant que responsables et en tant que personnes contribuant chez {ref}, à faire de la participation une expérience exempte de harcèlement pour tout le monde, quel que soit le niveau d’expérience, le sexe, l’identité ou l’expression de genre, l’orientation sexuelle, le handicap, l’apparence personnelle, la taille physique, l’origine ethnique, l’âge, la religion ou la nationalité.

== Nos critères

Exemples de comportements qui contribuent à créer un environnement positif :

* l’utilisation d’un langage ouvert et accueillant ;
* le respect des différents points de vue et expériences vécues ;
* accepter poliment les critiques constructives ;
* se concentrer sur ce qui est meilleur pour la communauté ;
* faire preuve d’empathie envers les autres membres de la communauté.

Exemples de comportements non acceptables :

* l’utilisation de langage ou d’imagerie sexualisés et les avances sexuelles non sollicitées ;
* le trolling, les commentaires insultants ou désobligeants, et les attaques personnelles ou d’ordre politique ;
* le harcèlement en public ou en privé ;
* la publication d’informations privées de tierces personnes, telles que des adresses physiques ou électroniques, sans permission explicite ;
* toute conduite qui pourrait être raisonnablement considérée comme inappropriée dans le milieu professionnel ;

== Nos responsabilités

Les Contributeurs de {ref} doivent clarifier les critères de comportement acceptables de toutes démarches contributives : il est attendu que ces personnes prennent les mesures correctives justes comme réponse à tout comportement inacceptable.

Les personnes responsable qui assurent l’organisation des démarches contributives ont le droit et la responsabilité de supprimer, modifier ou rejeter les commentaires, documents, modifications, questions et autres contributions qui ne respectent pas ce Code de Conduite des Contributeurs, ou de bannir temporairement ou définitivement quiconque d’une démarche contributive, suite à des comportements jugés inappropriés, menaçants, injurieux, ou nuisibles.

== Objectifs

Ce Code de Conduite des Contributeurs s’applique à la fois au sein des espaces physique et virtuel de {ref} ainsi que dans les espaces publics lorsqu’un individu représente un projet ou sa communauté. Font parties des exemples de représentation d’un projet ou d’une communauté le fait d’utiliser une adresse e-mail propre à un projet, de poster sur les réseaux sociaux avec un compte officiel, ou d’intervenir pour représenter le projet au cours d’un événement en-ligne ou hors-ligne. La représentation d’un projet pourra être autrement définie et clarifiée par les responsables desdits projets.

== Application

Les cas de comportements abusifs, harcelants ou tout autre comportement inacceptable peuvent être signalés en contactant l’équipe de {ref} à {email}. Toutes les plaintes seront examinées et étudiées et se traduiront par une réponse appropriée aux circonstances. L’équipe de {ref} s’engage à garder confidentielles les informations de la personne qui remonte un incident. Plus de détails sur la politique de mise en application des règles peuvent être publiés séparément.

Les Contributeurs qui ne suivent ou qui n’appliquent pas le Code de Conduite des Contributeurs de bonne foi s’exposent temporairement ou de façon permanente à des répercussions définies par les responsables de {ref}.

+++<br/>+++
+++<br/>+++
+++<br/>+++
+++<br/>+++
+++<br/>+++

[.underline]#Mention légale# :

Le présent Code de Conduite des Contributeurs (CCC) utilisé par {ref} est une copie à l'identique d'un document faisant partie du système Kalix créé par http://kalix.ch. Ce Code de Conduite est basée sur une version modifiée du Contributor Covenant, version 1.4, disponible à l’adresse https://www.contributor-covenant.org/fr/version/1/4/code-of-conduct. Ce document peut être utilisé, étudié, copié, modifié et distribuée selon les principes de la Déclaration de Biens Communs Numérisés disponible à l'adresse http://kalix.ch/declaration-de-biens-communs-numerises/. La licence CC BY-SA 4.0 International s’applique.
